import path from "node:path";
import { listFiles, pathExists, readText } from "../utils/file.js";

export async function buildProjectProfile(root: string): Promise<string> {
  const parts: string[] = ["# Project Context", "", "Generated by `skillbook profile`.", ""];
  const readme = path.join(root, "README.md");
  if (await pathExists(readme)) {
    parts.push("## README Summary", (await readText(readme)).slice(0, 1200), "");
  }
  const packageJson = path.join(root, "package.json");
  if (await pathExists(packageJson)) {
    parts.push("## package.json", "```json", (await readText(packageJson)).slice(0, 1200), "```", "");
  }
  const docs = (await listFiles(path.join(root, "docs"), ".md")).slice(0, 20).map((file) => path.relative(root, file));
  const src = (await listFiles(path.join(root, "src"), ".ts")).slice(0, 40).map((file) => path.relative(root, file));
  parts.push("## Docs", docs.length ? docs.map((item) => `- ${item}`).join("\n") : "- No docs found.", "");
  parts.push("## Source Structure", src.length ? src.map((item) => `- ${item}`).join("\n") : "- No src files found.", "");
  parts.push("## Current MVP Boundaries", "- Local filesystem and CLI first.", "- No Web UI, database, cloud sync, or real vector store in v1.");
  return `${parts.join("\n")}\n`;
}
